######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 29 17:20:05 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . bak
INCLUDEPATH += .

# Input
HEADERS += mainWindow.h bak/errnoent.h bak/syscallent.h
SOURCES += main.cpp mainWindow.cpp
RESOURCES += resource.qrc
