######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 30 11:53:06 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainWindow.h
SOURCES += main.cpp mainWindow.cpp
RESOURCES += resource.qrc
